dataset_name: csi
train_split: ['validation']
val_split: ['test']
dataset: {
  json_file: /home/lzdjohn/actionformer/csi_signal/csi_annotations/thumos_gt.json,
  feat_folder: /home/lzdjohn/actionformer/csi_signal/signal/,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 7,
  input_dim: 30,
  feat_stride: 16,
  num_frames: 2000,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
  # max_seq_len: 4608,
  # max_seq_len: 9216,
  # serve as data augmentation
}
model: {
  input_dim : 30,
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 19, # 本身是19
}
# python ./train_csi.py ./configs/csi.yaml --output reproduce
# python ./train_csi.py ./configs/csi.yaml --output reproduce
opt: {
  # learning_rate: 0.0001,
  learning_rate: 0.01,
  epochs: 30,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: ./ckpt/
